### ISSUE TITLE
E-store Database Structure Analysis

### ISSUE THREAD

**Issue by msh-shf** [luyadev/luya-module-estore#10]
Hi nadar, I have some questions about estore database structure and
I’ll be happy if you guide me.
Questions:
1-	Why database structure based on migration is different from ERD in Github documentation (https://github.com/luyadev/luya-module-estore)
In particular the relations between estore_article, estore_article_attribute_value, estore_set and estore_set_attribure.

![estore_erd](https://user-images.githubusercontent.com/12235182/48296856-469f7600-e4b1-11e8-9f6b-7666f0ec53be.png)

2-	What is the difference between tables `estore_group` and `estore_set`?
3-	The products images must save in which table?
4-	Why don’t you consider about discount percent, have to save in `estore_product` table or `estore_article`?
5-	Why are there fields `set_id` and `attribute_id` in table `estore_article_attribure_value`? Don’t this table have to reference to `estore_set_attribure_ref` table? If not so what is the usage of `estore_set_attribure_ref`?
6-	What is the difference between `qty_available` in `estore_article` and `qty` in `estore_article_price` table?
7-	What is `sku` field in table `estore_article`?
8-	What is the usage of `is_base` in table `estore_currency`?
9-	Why is there field `name`  in table `estore_article`? What is the usage of field `name` in table `estore_product`?
10-	Could you please provide some sample data with these tables? For example to define product attributes in table `estore_set_attribute`, What should be values field if the attribute is multi-select?
11-	How these tables have to communicate with payment and invoces?
Thanks.

**Comment by nadar** [comment]
Hi @mhd-shf 

Thanks for the questions.

1. I have to check this - its in **heavy development** ☠️  phase and yes indeed the ERD seems to be outdated, i will refresh the ERD picture and check the relations, maybe something is not needed or outdated (columns) - what would you say? Do you have inputs?
2. Group: It is like a category in order to display those groups in frontend. Set: This is more of an internal set option, assuming you have Trousers - this could be a set, but the group cold be: Wearables.
3. Good point! It is not defined yet, maybe creating a table product_images table or sth, not defined. Inputs welcome.
4. This is not defined yet, i assume we need a redeem table where this information is stored.
5. I have to check this, maybe also part of refactor check in 1.
6. price qty: this defines what is the price for the given quantity - this allows you to make something cheaper when ordering 2 of them, for example. article qty_available: How many items are available in your stock - so you know how many you can sale.
7. stock keeping unit: https://en.wikipedia.org/wiki/Stock_keeping_unit
8. If you like to dynamic calculate price for currency you can say which is the base currency in order to calculate them (EUR -> CHF, EUR -> USD, EUR -> RUB) (assuming EUR is_base)
9. Article name: XXL Red, Product name: Armani Trousers
10. We can provide screenshots.
11. Customer data is not involved - we would like to connect this module to (https://github.com/luyadev/luya-module-account which is in development mode as well) - and for payment we will use: https://github.com/luyadev/luya-module-payment

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.

**Comment by siripravi** [comment]
![LuyaEstore](https://github.com/luyadev/luya-module-estore/assets/174201/3bec6a3e-2b7d-493a-a4af-80c2870fd258)
Can this be used?

**Comment by nadar** [comment]
wo do not further develop this module - you can fork it and do whatever you like 👍
